spring:
  application:
    name: CoffeeMachine

  datasource:
    url: jdbc:postgresql://localhost:5432/coffeemachine
    username: topuser
    password: SomePassword1997
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    locations: classpath:db/migration